### ISSUE TITLE
update local sql database

### ISSUE THREAD

**Issue by gnzsnz** [theOGognf/finagg#49]
hi,

i'm playing with your module and so far i find it really nice.

I'm wondering how to update the sqlite db. I did a install a few months ago and i'm wondering if i can put it up to date. but when i check the CLI documentation is talks about a fresh install. if possible i would like to add new values rather that start from zero. but i can't find a way to do it.

**Comment by theOGognf** [comment]
Great question. There's no feature yet to update rather than install from scratch; this would be a good added feature. I'll keep track of this and work on it when I get the chance. Always welcome for someone else to try it themselves as well

**Comment by gnzsnz** [comment]
i'll give it a look, but i can't promise much. thanks for adding this as an enhacement, given the amount of time it takes to have a fully working initial set-up this would be more than a nice to have.

i have right now 28Gb of data downloaded from the initial install, and unfortunatelly is already obsolete.

**Comment by theOGognf** [comment]
In the meantime and if you aren't already doing this use the API implementations if you need more up-to-date data on-demand. That may be the recommended way to explore data unless you're doing large scale analysis frequently

**Comment by theOGognf** [comment]
Is this still desired by anyone else? May have time to work it this weekend, but looking for more interest from other folks. May leave this open until there's more interest

**Comment by gnzsnz** [comment]
I'm still here 🤗

**Comment by theOGognf** [comment]
Finally got some time to begin working this (life is busy). This is a bigger task than I thought. We need to add an update method for each table and a lot of tables have dependencies on one another, so there's a lot of funny business going on when updating. Updating isn't very trivial for the SEC submodule either. To check if an update is even necessary for it, we'd need to query all the companies we have data for, which by itself is pretty time consuming. I'm going to break this up into the respective items that need updating to enable this feature:

- [ ] yfinance prices features
- [ ] yfinance daily features
- [ ] SEC submissions features
- [ ] SEC tags features
- [ ] SEC quarter features (including normalized and industry)
- [ ] SEC annual features (including normalized and industry)
- [ ] fundam features (including normalized and industry)

**Comment by theOGognf** [comment]
Tracking the yfinance tasks here https://github.com/theOGognf/finagg/tree/yf-update-cli

**Comment by theOGognf** [comment]
So, I did some timing testing with the remaining features. It takes significantly longer to test whether there are new SEC filings instead of just installing them all new again, making an update feature not very useful. Good news is the yfinance update features are already merged in and do provide good speed benefits. Since yfinance was the main bottleneck anyways, this should still provide a good time improvement overall, even without the remaining update features

Thanks again for bringing this issue up
