### ISSUE TITLE
BEA vs FRED

### ISSUE THREAD

**Issue by firmai** [theOGognf/finagg#50]
You mention that FRED data can be used instead of BEA, but FRED data looks quite scattered, do you have a guide, or have you replicated the data before, thanks.

**Comment by firmai** [comment]
The reason I am asking is the BEA class seems finicky, 

```
---------------------------------------------------------------------------

BEAAPIError                               Traceback (most recent call last)

[<ipython-input-22-d5c511c96089>](https://localhost:8080/#) in <cell line: 2>()
      1 import finagg
----> 2 grab = finagg.bea.api.gdp_by_industry.get(year=[2019], api_key="my key")

1 frames

[/usr/local/lib/python3.10/dist-packages/finagg/bea/api.py](https://localhost:8080/#) in _get(params, api_key)
    516     if "Error" in content:
    517         error = _api_error_as_response(content["Error"])
--> 518         raise BEAAPIError(response.request, error, error.content)
    519     if "Error" in content["Results"]:
    520         error = _api_error_as_response(content["Results"]["Error"])

BEAAPIError: [Errno GET https://apps.bea.gov/api/data?DatasetName=GdpByIndustry&Frequency=Q&Industry=ALL&Method=GetData&TableID=ALL&UserID=21B1E0AE-F346-4097-9C01-AE8433E839FB&Year=2019] <Response [204]>: b'{"APIErrorDescription": "Error retrieving GDP by Industry data.", "ErrorDetail": {"Description": "Quarterly GDP by industry tables will be available later this fall."}}'

```

**Comment by theOGognf** [comment]
The BEA API itself is quite finicky indeed; it's younger and still finding its footing I think. The FRED API is pretty comprehensive, and more reliable in comparison (albeit overwhelming). Probably an unsatisfying answer, but I recommend you use `finagg.fred.series.search` to search through data series that you're interested in, and then filter through the series yourself

Something like `finagg.fred.api.series.search.get("Real Gross Domestic Product United States")` returns a lot of seemingly relevant series, but mostly split according to state. You could then write a regex to filter on the title and then continue to aggregate from there (something like `(?<=Real Gross Domestic Product: )(.*?)(?= in (Alabama|Alaska|...))` maybe?)

**Comment by firmai** [comment]
Thanks, good answer
