### ISSUE TITLE
Getting well structured financial statements

### ISSUE THREAD

**Issue by jegauth** [theOGognf/finagg#52]
Hello! I am a new user of finagg. I would like a well structured of any financial statements (cashflow statement, balance sheet and income statement) for many years. For instance, I would like to get the financial statements for AAPL for the last 10 years in a dataframe. Can I do that simply using finagg? Thanks in advance!

**Comment by theOGognf** [comment]
Hey there -- probably the closest thing to what you're asking for is something like:

```python
import finagg

df = finagg.sec.api.company_concept.join_get(finagg.sec.api.popular_concepts, ticker="AAPL")
```

Bit of an explanation:

- a company concept is a company's XBRL disclosure (basically a financial attribute)
- `finagg.sec.api.company_concept` is finagg's SEC EDGAR API company concept implementation
- The `finagg.sec.api.company_concept.join_get` method is just a helper for joining multiple concepts together into one dataframe
- `finagg.sec.api.popular_concepts` is a list of popular concepts available from the SEC EDGAR API. There are probably way more XBRL disclosures that you'd be interested in, but quarterly filings aren't audited, so you may not get much luck in getting all the data you want. You should explore the available XBRL disclosures for each company to see what you can get (try using the `finagg.sec.api.submissions` class instance to see what's available for a company)

If you find other disclosures that AAPL supports, you just need to pass them to that `finagg.sec.api.company_concept.join_get` method to get all the data in a single dataframe. Hope this helps!

**Comment by theOGognf** [comment]
You should check out the example provided in the `finagg.sec.api.join_filings` [docstring](https://github.com/theOGognf/finagg/blob/ce72817ecb794be16e0e7345b726c62783cedad4/src/finagg/sec/api.py#L1021) (provided below with comments for convenience):

```python
df = finagg.sec.api.company_facts.get(ticker="AAPL")  # get all data associated with AAPL
df = finagg.sec.api.get_unique_filings(df, form="10-K")  # get all unique annual filings
df = finagg.sec.api.join_filings(df, form="10-K")  # pivot the table for convenience
```

The final `df` should be the closest thing to what you want. You'll have to look through the returned columns to see if everything you want is in there. Just stressing: the SEC EDGAR API is still relatively new - it may not contain all the information you're looking for, but it is the best source of information that I'm aware of. Whether you use finagg to get that data doesn't matter as much - any library you use will likely be pulling from the SEC EDGAR API

**Comment by jegauth** [comment]
Hello theOGognf! I have a little question for you. When I go on quickfs.net or Seeking Alpha I got these result for the gross profit: 

![image](https://github.com/theOGognf/finagg/assets/116890061/533d0636-258c-4b49-a19f-8f1871a6f3dc)

When I use your code

```
df = finagg.sec.api.company_facts.get(ticker="AAPL")  # get all data associated with AAPL
df = finagg.sec.api.get_unique_filings(df, form="10-K")  # get all unique annual filings
df = finagg.sec.api.join_filings(df, form="10-K")  # pivot the table for convenience
```
I got this result

![image](https://github.com/theOGognf/finagg/assets/116890061/37e30bc7-dfb0-4fee-9538-b3bbd9a18322)

Just one example, look at the gross profit in FY 2023, i.e. 1.5283e+11, and look where it is located in the spreadsheet. The same result is located in year 2021. So it is delayed by almost 2 years. Is it normal? There might be an issue somewhere. Can you look at it
