### ISSUE TITLE
Getting the float and the number of shares outstanding

### ISSUE THREAD

**Issue by jegauth** [theOGognf/finagg#53]
Hello! Do you have an idea how could I get the float (= shares outstanding - restricted shares) and the number of shares outstanding for the last couple of year for any stock? For instance, I would like to get the float and the number of shares outstanding for AAPL in the last 10 years in a nice pandas dataframe. Thanks in advance!

P.S. I would say the float is the most important part for me.

**Comment by theOGognf** [comment]
Hey @jegauth, I appreciate your interest in finagg, but the project's issues isn't an appropriate place to ask questions regarding wrangling XBRL data 😅. Project issues should be focused on finagg -specifics, like features, bugs, or questions when the documentation is insufficient

However, I did just enable the discussions board, so feel free to ask more questions there

I'm happy to point you in the right direction on this board this one time though; continuing from the other issue's [comment](https://github.com/theOGognf/finagg/issues/52#issuecomment-2009615520), you can find the column whose name most closely matches "float" and that would be your answer, or fine the columns whose names most closely match "sharesoutstanding" and "restrictedshares" and take their difference, respectively, to get a new series that is the float

You can use Python's [difflib](https://docs.python.org/3/library/difflib.html) to find the columns that most closely match with other strings as a starting point

**Comment by jegauth** [comment]
I really appreciate your work so far! It seems really useful so fall!! Thanks for your time!
