### ISSUE TITLE
Upgrade to Pandas 2.*

### ISSUE THREAD

**Issue by jragbeer** [theOGognf/finagg#56]
Hello, 
Thanks for the project! Very helpful!

Is there an appetite to upgrading to pandas 2.* ?

**Comment by theOGognf** [comment]
Sure, I can bump pandas tomorrow after work and bump the major version of finagg as well

**Comment by jragbeer** [comment]
Thanks!

**Comment by theOGognf** [comment]
Pandas bumped to 2.* and finagg was bumped to 1.0.0. Cheers
