### ISSUE TITLE
 turn off caching 

### ISSUE THREAD

**Issue by zero-stroke** [theOGognf/finagg#57]
How can you completely turn off caching so that you get a fresh request every time an api call is made?

**Comment by theOGognf** [comment]
Hmmm, I’m not sure if there’s an easy way to do that without updating finagg. I can add an env variable to disable caching - would that work?

**Comment by zero-stroke** [comment]
Yes, that would be a great addition and an env variable is an intuitive way to do it.

**Comment by theOGognf** [comment]
Give the main branch a shot (31cf271ee6ad8de9fc2485194fba0d262e1b3f45) and let me know if that suits your expectations. The tests may show as failing because of the BEA API smoke tests (BEA has an unreliable API)

**Comment by zero-stroke** [comment]
This is much better. At first I was confused because I was trying to do it this way: 
```
from finagg import fred
import os
os.environ["FINAGG_DISABLE_HTTP_CACHE"] = "True"
```

But then I realized if I want to set it with os I have to do that before importing from finagg. I've just set it system wide anyways though so its easier, thanks for this change.

**Comment by theOGognf** [comment]
I’ll find some time to push a small release with the change to PyPi this weekend

**Comment by theOGognf** [comment]
Closed with new release https://github.com/theOGognf/finagg/releases/tag/1.0.2
